[package]
name = "midly"
version = "0.1.3"
edition = "2018"
authors = ["negamartin"]
include = [
  "/src/*",
  "/Cargo.toml",
]
description = "A pure-rust fast and flexible MIDI parser library, designed for multi-MB files"
repository = "https://github.com/negamartin/midly"
readme = "README.md"
keywords = ["parser", "audio", "midi"]
categories = ["multimedia", "multimedia::audio", "multimedia::encoding"]
license = "Unlicense"

[features]
default = ["std"]

# Whether to enable use of the standard library and multithreaded midi parsing.
# Enabled by default.
std = ["rayon", "failure/std"]

# Do a "best-attempt" at decoding the file, even if it's obviously corrupted.
#
# No `ErrorKind::Malformed` errors will be raised.
# Tracks with invalid events will be dropped.
lenient = []

# Reject files that bend the standard.
#
# `ErrorKind::Pedantic` errors will be raised.
# The `MetaEvent::Unknown` event kind is promoted to a pedantic error.
strict = []

[dependencies]
failure = { version="0.1", default-features=false, features=["derive"] }
rayon = { version="1.1", optional=true }
