[package]
name = "midly"
version = "0.1.3"
edition = "2018"
authors = ["negamartin"]
include = [
  "/src/*",
  "/Cargo.toml",
]
description = "A Rusty ultra-fast, safe, easy to use MIDI parsing library designed for multi-MB files"
repository = "https://github.com/negamartin/midly"
readme = "README.md"
keywords = ["parser","audio"]
categories = ["multimedia","multimedia::audio","multimedia::encoding"]
license = "Unlicense"

[features]

# Do a "best-attempt" at decoding the file, even if it's obviously corrupted.
#
# No `ErrorKind::Malformed` errors will be raised.
# Tracks with invalid events will be dropped.
lenient = []

# Reject files that bend the standard.
#
# `ErrorKind::Pedantic` errors will be raised.
# The `MetaEvent::Unknown` event kind is promoted to a pedantic error.
strict = []

[dependencies]
failure = "0.1"
bit = "0.1"
rayon = "1.1"
